name: PR Discord Notification

on:
  pull_request:
    types: [opened, synchronize, reopened, review_requested]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          username: "GitHub Monitor"
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
          color: "483D8B" # Màu tím tối sang trọng
          message: |
            ### 🚀 New Pull Request Update
            **Title:** ${{ github.event.pull_request.title }}
            **Author:** ${{ github.event.pull_request.user.login }}
            **Commit:** `${{ github.event.pull_request.head.sha }}`
            **Status:** ${{ github.event.pull_request.state }}
            
            **Reviewers:** ${{ join(github.event.pull_request.requested_reviewers.*.login, ', ') || 'None assigned' }}
            
            **Description:** > ${{ github.event.pull_request.body || 'No description provided.' }}
            
            [View Pull Request](${{ github.event.pull_request.html_url }})